### ISSUE TITLE
Plugin never returns true for isTracked

### ISSUE THREAD

**Issue by JeffP07** [Flo0/PlayerBlockTracker#1]
This plugin is exactly what I needed for one of my projects, however it never returns that a block is being tracked. The isTracked function always returns false. Doing a little digging, it seems like TrackedChunk#isTracked always returns false despite me placing blocks.

Server: purpur 1.16.5 build #1119

**Comment by Flo0** [comment]
Did you place them in creative? Because Blocks placed in creative mode dont get tracked.

**Comment by JeffP07** [comment]
No, I was testing in survival, 

Edit; I made a fresh test server with just PlayerBlockTracker and it still comes out the same where isTracked always returns false

**Comment by JeffP07** [comment]
I just tried with a fresh spigot server, instead of purpur, and it seems to have the same issue still

**Comment by Flo0** [comment]
Ive found the problem. There was a weird behavior with the bit shifting and some chunks in negative sections.
It should be fixed now :D
