### ISSUE TITLE
isTracked returning false when the block is broken

### ISSUE THREAD

**Issue by kielkucki** [Flo0/PlayerBlockTracker#2]
Hi, I am trying to make a plugin that gives a reward for breaking natural blocks and when they break a block they placed, it will give them the vanilla block. Is the value supposed to be false on block break even if I don't untrack the block?

**Comment by kielkucki** [comment]
It won't work in a BlockDropitemEvent

**Comment by Flo0** [comment]
The blocks get automatically tracked in the BlockPlaceEvent and released in the BlockBreakEvent.
If you want to detect player placed blocks in the BlockDropitemEvent then you need to forward the
Block from the BlockBreakEvent. Should be quite easy to do.
